name: Update release branch
on:
  pull_request:
    types: [labeled]

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Merge develop -> release branch
        uses: devmasx/merge-branch@master
        with:
          label_name: 'release'
          from_branch: develop
          target_branch: release/canyonlands #${{steps.get_release.outputs.tag_name}}
          github_token: ${{ secrets.GITHUB_TOKEN }}