name: Release
on:
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get release information
        id: get_release
        uses: cardinalby/git-get-release-action@1.2.2
        with:
          latest: true
      
    #   - name: Print release information
    #     run: |
    #       echo "Steps: ${{toJson(steps)}}"
    #       echo "get_release: ${{steps.get_release}}"
    #       echo "Outputs: ${{steps.get_release.outputs}}"
    #       echo "tag_name: ${{steps.get_release.outputs.id}}"
    #       echo "tag_name: ${{steps.get_release.outputs.name}}"
    #       echo "tag_name: ${{steps.get_release.outputs.body}}"
    #       echo "tag_name: ${{steps.get_release.outputs.tag_name}}"
    #       echo '${{ toJSON(github) }}'   



      - name: Create release branch
        id: create_release
        uses: peterjgrainger/action-create-branch@v2.2.0
        with:
          branch: 'release/${{steps.get_release.outputs.tag_name}}'

      # - name: Increment POM versions
      # Need to figure out how to determine which versions need incrementing

    #   - name: Merge develop -> release branch
    #     uses: devmasx/merge-branch@master
    #     with:
    #       label_name: 'Merging develop into release branch'
    #       from_branch: develop
    #       target_branch: release/${{steps.get_release.outputs.tag_name}}
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
          ref: develop

      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: Jxsephh/github-actions-test
          path: github-actions-test
          ref: master