name: Release
on:
  push:
  # release:
  #   types: [published]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:      
      - name: Print envs
        run: |
          echo '${{ toJSON(github) }}'   
          echo '${{ toJSON(env) }}'

      - name: Checkout other repo
        uses: actions/checkout@v3
        with:
          repository: Jxsephh/github-actions-test
          ref: develop
          fetch-depth: '0'
        
      - name: Check for changes in repo
        run: | 
          git status
          diff = git diff develop origin/master

      - name: Display changes
        run: echo $diff



      ## WIP ##
      # - name: Get release information
      #   id: get_release
      #   uses: cardinalby/git-get-release-action@1.2.2
      #   with:
      #     latest: true

      # - name: Create release branch
      #   id: create_release
      #   uses: peterjgrainger/action-create-branch@v2.2.0
      #   with:
      #     branch: 'release/${{steps.get_release.outputs.tag_name}}'

      # - name: Increment POM versions
      # Need to figure out how to determine which versions need incrementing

    #   - name: Merge develop -> release branch
    #     uses: devmasx/merge-branch@master
    #     with:
    #       label_name: 'Merging develop into release branch'
    #       from_branch: develop
    #       target_branch: release/${{steps.get_release.outputs.tag_name}}
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     path: main