name: Release
on:
  push:
  # release:
  #   types: [published]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  update-dependencies:
    name: Update dependency versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scripts
        uses: actions/checkout@v3 
        with:
          ref: master

      - name: Checkout other repo
        uses: actions/checkout@v3
        with:
          repository: Jxsephh/github-actions-test
          path: github-actions-test
          ref: develop
          fetch-depth: '0'
        
      - name: Check for changes in repo
        run: |
          echo "UPGRADE_SOAPLIB="$(./.github/scripts/check-changes-across-branches.sh github-actions-test develop origin/master) >> $GITHUB_ENV
        shell: bash

      - name: Upgrade pom.xml versions
        run: |
          if [ "$UPGRADE_SOAPLIB" = "1" ] ; then
            echo "Soaplib has changes, upgrading version in pom.xml"
            echo $(mvn help:evaluate -Dexpression=soapLib.version -q -DforceStdout)
            mvn versions:set-property -Dproperty=soapLib.version -DgenerateBackupPoms=false -DnewVersion=54 -q -DforceStdout
            echo $(mvn help:evaluate -Dexpression=soapLib.version -q -DforceStdout)
            echo "UNCOMMITED_CHANGES="false >> $GITHUB_ENV
          else
            echo "Soaplib has no new changes, skipping..."
          fi

        env:
          UPGRADE_SOAPLIB: ${{ env.UPGRADE_SOAPLIB }}

      - name: Commit updates
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ env.UNCOMITTED_CHANGES == true }}
        with:
          branch: develop
          commit_message: "Upgrading dependency versions"

  create-release:
    name: Create release branch
    needs: [update-dependencies]
    runs-on: ubuntu-latest
    steps:
      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        with:
          branch: 'release/canyonlands'
      
      - name: Merge develop -> release branch
        uses: devmasx/merge-branch@master
        with:
          label_name: 'Merging develop into release branch'
          from_branch: develop
          target_branch: release/canyonlands
          github_token: ${{ secrets.GITHUB_TOKEN }}



      ## WIP ##
      # - name: Get release information
      #   id: get_release
      #   uses: cardinalby/git-get-release-action@1.2.2
      #   with:
      #     latest: true

      # - name: Create release branch
      #   id: create_release
      #   uses: peterjgrainger/action-create-branch@v2.2.0
      #   with:
      #     branch: 'release/${{steps.get_release.outputs.tag_name}}'

      # - name: Increment POM versions
      # Need to figure out how to determine which versions need incrementing

    #   - name: Merge develop -> release branch
    #     uses: devmasx/merge-branch@master
    #     with:
    #       label_name: 'Merging develop into release branch'
    #       from_branch: develop
    #       target_branch: release/${{steps.get_release.outputs.tag_name}}
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     path: main