name: Release
on:
  push:
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get release
        id: get_release
        run: |
          echo "Steps: ${{toJson(steps)}}"
          echo "get_release: ${{steps.get_release}}"
          echo "Outputs: ${{steps.get_release.outputs}}"
          echo "tag_name: ${{steps.get_release.outputs.tag_name}}"

      # - name: Create release branch
      #   uses: peterjgrainger/action-create-branch@v2.2.0
      #   id: get_release
      #   with:
      #     branch: 'release/${{steps.get_release.outputs.tag_name}}'

      # # - name: Increment POM versions
      # # Need to figure out how to determine which versions need incrementing

      # - name: Merge develop -> release branch
      #   uses: devmasx/merge-branch@master
      #   with:
      #     label_name: 'Merging develop into release branch'
      #     from_branch: develop
      #     target_branch: release/${{steps.get_release.outputs.tag_name}}
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
