name: Release
on:
  release:
    types: [published]

# env:
  # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
# jobs:
#   create-release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get Release
#         id: get_release

#       - name: Create release branch
#         uses: peterjgrainger/action-create-branch@v2.2.0
#         with:
#           branch: 'release/${{steps.get_release.outputs.tag_name}}'
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#       # - name: Increment POM versions
#       # Need to figure out how to determine which versions need incrementing

#       - name: Merge develop -> release branch
#         uses: devmasx/merge-branch@master
#         with:
#           label_name: 'Merging develop into release branch'
#           from_branch: develop
#           target_branch: release/${{steps.get_release.outputs.tag_name}}
#           github_token: ${{ secrets.GITHUB_TOKEN }}
          