name: Create release
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release branch name'
        required: true
      nrs_version:
        description: 'New version of NRS'
        required: true
      soaplib_version:
        description: 'New version of SOAPLIB'
        required: false
      restlib_version:
        description: 'New version of RESTLIB'
        required: false
      pr_title:
        description: 'Pull request title'
        required: true
      pr_body:
        description: 'Pull request description'
        required: false
env: 
  BODY_NRS_VERSION: ""
  BODY_NRS_SOAP_VERSION: ""
  BODY_NRS_REST_VERSION: ""
  BODY_NRS_CLIENT_VERSION: ""
jobs:           
  update-dependencies:
    name: Update dependency versions and create release PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
        with:
          path: main
          ref: master

      - name: Checkout SOAPLIB code
        uses: actions/checkout@v3
        with:
          repository: Jxsephh/github-actions-test
          path: github-actions-test
          ref: develop
          fetch-depth: '0'

      - name: Update dependency versions in pom.xml
        run: |
          cd main
          mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${{ inputs.nrs_version }} -q -DforceStdout
          echo "BODY_NRS_VERSION=[nrs " ${{ inputs.nrs_version }} "]("${{ steps.cpr.outputs.pull-request-url }}")" >> $GITHUB_ENV
          echo $BODY_NRS_VERSION

          if [ ! -z ${{ inputs.soaplib_version }} ] ; then
            echo "Updating SOAPLIB version"
            mvn versions:set-property -Dproperty=soapLib.version -DgenerateBackupPoms=false -DnewVersion=${{ inputs.soaplib_version }} -q -DforceStdout
            echo "BODY_NRS_SOAP_VERSION= | [nrs soap " ${{ inputs.soaplib_version }} "](https://github.com/AAInternal/nrs-soaplib/pull/)" >> $GITHUB_ENV
          fi

          if [ ! -z ${{ inputs.restlib_version}} ] ; then
            echo "Updating RESTLIB version"
            mvn versions:set-property -Dproperty=restLib.version -DgenerateBackupPoms=false -DnewVersion=${{ inputs.restlib_version }} -q -DforceStdout
            echo "BODY_NRS_REST_VERSION= | [nrs rest " ${{ inputs.restlib_version }} "](https://github.com/AAInternal/nrs-restlib/pull/)" >> $GITHUB_ENV
            echo "BODY_NRS_CLIENT_VERSION= | [nrs client " ${{ inputs.nrs_version }} "](https://github.com/AAInternal/nrs-client/pull/)" >> $GITHUB_ENV
          fi

      - name: Create pull request and commit updates
        id: cpr
        uses: peter-evans/create-pull-request@v4.1.1
        with:
          base: master
          branch: ${{ inputs.release_name }}
          commit-message: "Updating dependency versions"
          draft: true
          path: main
          reviewers: Jxsephh
          title: ${{ inputs.pr_title }}
          body: | 
            ${{ inputs.pr_body }}
            ### Included stories:
            -**US.....:**

            ---
            ### Related versions:
            ${{ env.BODY_NRS_VERSION }} ${{ env.BODY_NRS_SOAP_VERSION }} ${{ env.BODY_NRS_REST_VERSION }} ${{ env.BODY_NRS_CLIENT_VERSION }}

      - name: Merge develop into release branch
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: develop
          target_branch: ${{ inputs.release_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: SOAPLIB Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        if: ${{ inputs.soaplib_version }} != ''
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: Jxsephh/github-actions-test
          event-type: update
          client-payload: '{"release_name": "${{ inputs.release_name }}", "soaplib_version": "${{ inputs.soaplib_version }}"},"pr_title": "${{ inputs.pr_title }}", "pr_body": "${{ inputs.pr_body }}'

      - name: RESTLIB Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        if: ${{ inputs.restlib_version }} != ''
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: Jxsephh/github-actions-test
          event-type: update
          client-payload: '{"release_name": "${{ inputs.release_name }}", "restlib_version": "${{ inputs.restlib_version }}", "pr_title": "${{ inputs.pr_title }}", "pr_body": "${{ inputs.pr_body }}'

      # - name: Update PR????
      #   id: cpr2
      #   uses: peter-evans/create-pull-request@v4.1.1
      #   with:
      #     base: master
      #     branch: ${{ inputs.release_name }}
      #     commit-message: "Updating dependency versions"
      #     draft: true
      #     path: main
      #     body: | 
      #       ${{ inputs.pr_body }}
      #       ### Included stories:
      #       -**US.....:**

      #       ---
      #       ### Related versions:
      #       ${{ env.BODY_NRS_VERSION }} ${{ env.BODY_NRS_SOAP_VERSION }} ${{ env.BODY_NRS_REST_VERSION }} ${{ env.BODY_NRS_CLIENT_VERSION }}

      - name: Generate Build Summary
        run: |
          echo '### Release PR Created!' >> $GITHUB_STEP_SUMMARY
          echo '**Pull Request URL:** [${{ steps.cpr.outputs.pull-request-url }}](${{ steps.cpr.outputs.pull-request-url }})' >> $GITHUB_STEP_SUMMARY.
  # update-snapshot:
  #   name: Update snapshot version in develop
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #       with:
  #         ref: develop
      
  #     - name: Update NRS version in pom.xml
  #       run:
  #         mvn versions:set-property -Dproperty=soapLib.version -DgenerateBackupPoms=false -DnewVersion=${{ inputs.soaplib_version }} -q -DforceStdout